OPENAI_API_KEY = "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"
APP_PASSWORD = "josquin1521"